
name: CI/CD
# 触发条件为 push
on: [push] # 执行时机
# 任务
jobs:
  test:
    # 运行的环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - uses: actions/checkout@v2 # git pull
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: 打包镜像, 上传 Docker Hub
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build -t nuxt-zhifei  .
          docker tag nuxt-zhifei registry.cn-hangzhou.aliyuncs.com/pengliang/nuxt-zhifei
          docker push registry.cn-hangzhou.aliyuncs.com/pengliang/nuxt-zhifei:latest

      - name: 登录服务器, 执行脚本
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop nuxt-zhifei
            docker rm nuxt-zhifei
            docker rmi registry.cn-hangzhou.aliyuncs.com/pengliang/nuxt-zhifei:latest
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull registry.cn-hangzhou.aliyuncs.com/pengliang/nuxt-zhifei:latest
            docker run --restart=always -d -p 10014:3000 --name nuxt-zhifei registry.cn-hangzhou.aliyuncs.com/pengliang/nuxt-zhifei:latest