name: Node.js Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Set permissions for a directory
      run: chmod -R 777 /home/runner/work/nuxt3-zhifei/nuxt3-zhifei/public

    - name: Debug information
      run: |
        echo "Current working directory: $(pwd)"
        ls -l /home/runner/work/nuxt3-zhifei/nuxt3-zhifei/public

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        
        script: |
          cd /www/wwwroot/nuxt-zhifei.pl-fe.cn
          rm -rf *     
          scp -r /home/runner/work/nuxt3-zhifei/nuxt3-zhifei/public .
          pm2 restart your-app-name
